version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: robzard
      POSTGRES_PASSWORD: Monster7816361189!
      POSTGRES_DB: botdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  bot:
    build: .
    depends_on:
      - db
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
      - ADMIN_ID=YOUR_ADMIN_TELEGRAM_ID
      - DATABASE_URL=postgresql+asyncpg://botuser:botpass@db:5432/botdb
    restart: always

volumes:
  postgres_data:
